### ISSUE TITLE
Certificate validation overwritten

### ISSUE THREAD

**Issue by gonzobrains** [infosupport/xamarin-security-scanner#1]
I just tried your app and received the following:

Code: CertificateValidation
Title: Certificate validation overwritten
SeverityLevel: High
Description: Certificate validation callback is overwritten. This may open the d
oor to man-in-the-middle attacks.

What is the solution if your app requires defining its own callback?  Is code obfuscation the only available protection?  Thanks!

**Comment by wesleydekraker** [comment]
You're receiving this warning, because you have enabled backups in your AndroidManifest.xml.

By enabling backups your application participates in Google's backup and restore infrastructure. This may be a problem if you're storing sensitive information that should not be stored in Google's cloud. If this isn't the case, than you can safely ignore the warning.

On the other hand, you can also disable backups by setting AllowBackup to false. This ensures that no backup or restore will ever be performed, even by a full-system backup.

In your case this isn't an option. Your suggestion of encrypting sensitive data at rest is tricky, because the decryption key should not be stored on the device itself. Let's say that you store this decryption key on a remote server, then you would also need to authenticate the user first before sending the key to the device. 

The best advice would be to not store any sensitive information on the device itself at all. Ideally the user would first authenticate when opening your app and then retrieve sensitive information from your back end. This strategy is used by banking apps and may be overkill for other applications.

**Comment by gonzobrains** [comment]
This response is a duplicate of the response for my other issue.  Could you
please reply again with a new answer?  Thanks.

**Comment by wesleydekraker** [comment]
That's strange. I corrected that mistake yesterday. Below you will find my response:

> You're receiving this warning, because you have overwritten the default certificate validation.
> 
> This validation ensures that you connect to the intended server. If you overwrite this validation incorrectly a man-in-the-middle attack may be possible. For example, this piece of code would be vulnerable:
> `ServicePointManager.ServerCertificateValidationCallback += (sender, cert, chain, sslPolicyErrors) => true;`
> 
> Could you share your snippet of code? Then I can provide further guidance.

**Comment by gonzobrains** [comment]
Could you explain how that code snippet would be vulnerable?  Is it because
it always returns true?  What are the correct ways over overriding the
validation?  In our case, we want to implement SSL certificate pinning.

**Comment by wesleydekraker** [comment]
Correct, that vulnerable piece of code will accept any certificate.

Implementing certificate pinning solves the issue and will greatly improve the security of your app. An example implementation for .NET can be found here:
https://owasp.org/www-community/controls/Certificate_and_Public_Key_Pinning

Another great resource is the OWASP Mobile Security Testing Guide.

The Xamarin Security Scanner currently doesn't detect certificate pinning. If you are still receiving this warning after you have implemented these changes, then you can safely ignore the warning.

**Comment by wesleydekraker** [comment]
@gonzobrains, I have created a separate issue to expand the description provided by the tool: https://github.com/wesleydekraker/xamarin-security-scanner/issues/1

If your question is resolved, please close this issue.

**Comment by simondel** [comment]
This repo has been moved to https://github.com/wesleydekraker/xamarin-security-scanner

If this issue/feature request still exists, please reopen your issue there.
