### ISSUE TITLE
Backups are enabled

### ISSUE THREAD

**Issue by gonzobrains** [infosupport/xamarin-security-scanner#2]
I just received the following warning:

Code: AllowBackup
Title: Backups are enabled
SeverityLevel: Medium
Description: Enabling backups may leak sensitive data to the cloud.

What is the solution for apps that require data to be backed up?  Encryption?  Please advise.   Thanks!

**Comment by wesleydekraker** [comment]
You're receiving this warning, because you have enabled backups in your AndroidManifest.xml.

By enabling backups your application participates in Google's backup and restore infrastructure. This may be a problem if you're storing sensitive information that should not be stored in Google's cloud. If this isn't the case, than you can safely ignore the warning.

On the other hand, you can also disable backups by setting AllowBackup to false. This ensures that no backup or restore will ever be performed, even by a full-system backup.

In your case this isn't an option. Your suggestion of encrypting sensitive data at rest is tricky, because the decryption key should not be stored on the device itself. Let's say that you store this decryption key on a remote server, then you would also need to authenticate the user first before sending the key to the device. 

The best advice would be to not store any sensitive information on the device itself at all. Ideally the user would first authenticate when opening your app and then retrieve sensitive information from your back end. This strategy is used by banking apps and may be overkill for other applications.

**Comment by wesleydekraker** [comment]
@gonzobrains, I have created a separate issue to expand the description provided by the tool: wesleydekraker/xamarin-security-scanner#2

Your feedback is much appreciated! If you have no further questions, please close this issue.

**Comment by simondel** [comment]
This repo has been moved to https://github.com/wesleydekraker/xamarin-security-scanner

If this issue/feature request still exists, please reopen your issue there.
