### ISSUE TITLE
is there an --output option as html or csv?

### ISSUE THREAD

**Issue by immi5556** [infosupport/xamarin-security-scanner#3]
that would be a nice feature.

**Comment by wesleydekraker** [comment]
Thank you for sharing that feature request! I will try to add it as soon as possible, probably at the end of this month. 

I am currently in the proces of moving the repository to my personal GitHub account: 
Could you close the issue here and recreate it at: https://github.com/wesleydekraker/xamarin-security-scanner? Thanks in advance.

**Comment by simondel** [comment]
This repo has been moved to https://github.com/wesleydekraker/xamarin-security-scanner

If this issue/feature request still exists, please reopen your issue there.
