### ISSUE TITLE
Code: AllowBackup - detected, even if set to false in androidmanifest.xml

### ISSUE THREAD

**Issue by immi5556** [infosupport/xamarin-security-scanner#4]
Steps:

In AndroidManifest.xml, Set both android:allowBackup="false" and  android:fullBackupContent="false"

Expected behavior: The Allowedbackup should not appear in the scan result.

Actual Behaviour: Still its appearing in the result.

**Comment by wesleydekraker** [comment]
Thank you for sharing the bug! I am able to reproduce the issue and I will try to resolve it soon.

I am currently in the process of moving the repository to my personal GitHub account:
Could you close the issue here and recreate it at: https://github.com/wesleydekraker/xamarin-security-scanner? Thanks in advance.

**Comment by simondel** [comment]
This repo has been moved to https://github.com/wesleydekraker/xamarin-security-scanner

If this issue/feature request still exists, please reopen your issue there.
